NAME: neuron
LAST DEPLOYED: Fri Jul  1 16:23:38 2022
NAMESPACE: default
STATUS: pending-install
REVISION: 1
USER-SUPPLIED VALUES:
{}

COMPUTED VALUES:
affinity: {}
autoscaling:
  enabled: false
  maxReplicas: 100
  minReplicas: 1
  targetCPUUtilizationPercentage: 80
clusterDomain: cluster.local
containerPorts:
  api: 7001
  web: 7000
fullnameOverride: ""
image:
  pullPolicy: IfNotPresent
  repository: emqx/neuron
  tag: ""
imagePullSecrets: []
ingress:
  annotations: {}
  className: ""
  enabled: false
  hosts:
  - host: chart-example.local
    paths:
    - path: /
      pathType: ImplementationSpecific
  tls: []
nameOverride: ""
nodeSelector: {}
persistence:
  accessMode: ReadWriteOnce
  enabled: true
  existingClaim: ""
  size: 20Mi
  storageClassName: ""
podAnnotations: {}
podSecurityContext: {}
readinessProbe:
  enabled: true
  initialDelaySeconds: 5
  periodSeconds: 5
replicaCount: 1
resources: {}
securityContext: {}
service:
  annotations: {}
  loadBalancerSourceRanges: []
  nodePorts:
    api: null
    web: null
  portNames:
    api: api
    web: web
  ports:
    api: 7001
    web: 7000
  type: ClusterIP
serviceAccount:
  annotations: {}
  create: true
  name: ""
tls:
  enabled: true
  privateKey: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEpAIBAAKCAQEAzrO7FUz4GGKl4nP5lwKMh5uageJAAHnLZpVxTR1wXA9E870s
    U03gHnPWsh2bXCCx85ymYaiu/5VlptgnU0rQB1I3xGRG8eHmHPrhHNWDRKpY6oY8
    AnTPqXvfa/Z4u+njJzDSqi4qM8Gwfqlgpjlg8DUF+sheLx8hL+x9XFzovTxafrmy
    JRRAVQTkhB7esKKqRF8BMjdOdYZxJEv9jxa0BwXcjprPDlj5TV6k3wJqbq4UtnEE
    VbjEQKqFVkfY4FuJ5NSPHpGEix94PGQGRsiWkGX0vx5udHJ0SlXM6qpMLny18FhW
    bwKNX3urc3mImn/j3zcJ5x1d+FlXAXs1NBSeTQIDAQABAoIBAQDJOT8PZXbAhohn
    A/AeimS0P08S0mbsD6VroGBEajxP4q2FeswD7PQZsTt4+kmcTlfuiLmQqN50AcSL
    wDHIbDRIbEnN7rECGKAj5jfwEgtQdWVKKpOQ8JaYr/a466BtjyuLo4PyGC8NY6mm
    JM3qBEHSlkvT7+uAhBWSye7gU7JfRPoCeFRpaMMC3Ad0DaIt/Pdt9CddNwj56+9j
    gl//blNnBImjvA7/kh9gL69SYVrQoG9vm/UgFbdIwd+w2hhhpx6kuHjRJ21xIV/y
    Yh9k4QhPr7zIkhQ8yn11ZhyZkMC8XAMy7NKCmAFIPNJ8jwvgBkunPEk2aYBeDUaq
    a30VwlIhAoGBAOnm8DW5DROcfSj4Q8zsvgmvhGM0zzF5zmA+4E+tEbf4t6sDUjSs
    ADo2EaiJZz75vLsD7UZHKzFEV/wnuT7SiNCbrJafx8Tp2UgijTkW8gEhAWREJDn5
    FS375RKFdEcpmVHWgsuz4z/0L3BGxmyYWQxx5pD2NL49ZpTIHAHm/XETAoGBAOI6
    8Y08TmM2bnXbL/MggYMJlqOyv27ueVYz9of3FYFAMIe7ebSgrlSCOwsoDZYmegBM
    OrowR3AAnoP4fjGNbIPjNYbiv1qLOdtnvPxYotEz+ZaUBSn9V/gUEVFlgrKxgTKr
    sqi/QMyyJplBTUkUuqYRDuv6TZ3OWKiDUoXTdv8fAoGBAIbbyf+PlESMY3Vtvtm2
    XdODyRbR6ewiyKShW/9UT/T8iBknrwwDZ5YoeoHrxwV+RBynpPRyMCsVto0B8kKQ
    bKWqPBYURb/4/Hgkw7v4yMtx1jWTPDfYryd2JptJKsOk7mtK/Nqp+wpypa9cfyc5
    p44PVdqauco96Jk7zzohjlrVAoGAfjQDrJaH5DDpTjYIeckYdtFSh9+fi3LdnYk/
    bnoYNRJqAE5Fhs5ccih0Z7TgX3L3fFMKL/Pe5kxyIYzuWRZcAvctVSIJPamNjShB
    9UQ9EBe+lJHej54VBP+s6YuHbcg4GtxNvnVy4L5Bah1T0AEQXrQFbv8jbXU/YEJi
    NuXQ7GECgYA0UNvuZxVSDn8fBxARcX3ub5aok5owdLL3SOCPMpNrmOBQj8iJGT+5
    nv7fH1TWVh9yUdRwhd81s5H/PO3/myLmgq0TcPvewtEEwY+++QpsYZwHTDXgxbbw
    ++lmJali4fzmd/72JqocGABYhZFt0jbcQ1QEcqUYcD380+cNVZPO+w==
    -----END RSA PRIVATE KEY-----
  publicKey: |
    -----BEGIN PUBLIC KEY-----
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAzrO7FUz4GGKl4nP5lwKM
    h5uageJAAHnLZpVxTR1wXA9E870sU03gHnPWsh2bXCCx85ymYaiu/5VlptgnU0rQ
    B1I3xGRG8eHmHPrhHNWDRKpY6oY8AnTPqXvfa/Z4u+njJzDSqi4qM8Gwfqlgpjlg
    8DUF+sheLx8hL+x9XFzovTxafrmyJRRAVQTkhB7esKKqRF8BMjdOdYZxJEv9jxa0
    BwXcjprPDlj5TV6k3wJqbq4UtnEEVbjEQKqFVkfY4FuJ5NSPHpGEix94PGQGRsiW
    kGX0vx5udHJ0SlXM6qpMLny18FhWbwKNX3urc3mImn/j3zcJ5x1d+FlXAXs1NBSe
    TQIDAQAB
    -----END PUBLIC KEY-----
tolerations: []

HOOKS:
---
# Source: neuron/templates/tests/test-connection.yaml
apiVersion: v1
kind: Pod
metadata:
  name: "neuron-test-connection"
  labels:
    helm.sh/chart: neuron-0.1.0
    app.kubernetes.io/name: neuron
    app.kubernetes.io/instance: neuron
    app.kubernetes.io/version: "2.0.1"
    app.kubernetes.io/managed-by: Helm
  annotations:
    "helm.sh/hook": test
spec:
  containers:
    - name: wget
      image: busybox
      command: ['wget']
      args: ['neuron:']
  restartPolicy: Never
MANIFEST:
---
# Source: neuron/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: neuron
  labels:
    helm.sh/chart: neuron-0.1.0
    app.kubernetes.io/name: neuron
    app.kubernetes.io/instance: neuron
    app.kubernetes.io/version: "2.0.1"
    app.kubernetes.io/managed-by: Helm
---
# Source: neuron/templates/tls-secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: neuron-certs
  namespace: default
  labels:
    helm.sh/chart: neuron-0.1.0
    app.kubernetes.io/name: neuron
    app.kubernetes.io/instance: neuron
    app.kubernetes.io/version: "2.0.1"
    app.kubernetes.io/managed-by: Helm
type: Opaque
data:
  neuron.pem: "LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUF6ck83RlV6NEdHS2w0blA1bHdLTQpoNXVhZ2VKQUFIbkxacFZ4VFIxd1hBOUU4NzBzVTAzZ0huUFdzaDJiWENDeDg1eW1ZYWl1LzVWbHB0Z25VMHJRCkIxSTN4R1JHOGVIbUhQcmhITldEUktwWTZvWThBblRQcVh2ZmEvWjR1K25qSnpEU3FpNHFNOEd3ZnFsZ3BqbGcKOERVRitzaGVMeDhoTCt4OVhGem92VHhhZnJteUpSUkFWUVRraEI3ZXNLS3FSRjhCTWpkT2RZWnhKRXY5anhhMApCd1hjanByUERsajVUVjZrM3dKcWJxNFV0bkVFVmJqRVFLcUZWa2ZZNEZ1SjVOU1BIcEdFaXg5NFBHUUdSc2lXCmtHWDB2eDV1ZEhKMFNsWE02cXBNTG55MThGaFdid0tOWDN1cmMzbUltbi9qM3pjSjV4MWQrRmxYQVhzMU5CU2UKVFFJREFRQUIKLS0tLS1FTkQgUFVCTElDIEtFWS0tLS0tCg=="
  neuron.key: "LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcEFJQkFBS0NBUUVBenJPN0ZVejRHR0tsNG5QNWx3S01oNXVhZ2VKQUFIbkxacFZ4VFIxd1hBOUU4NzBzClUwM2dIblBXc2gyYlhDQ3g4NXltWWFpdS81VmxwdGduVTByUUIxSTN4R1JHOGVIbUhQcmhITldEUktwWTZvWTgKQW5UUHFYdmZhL1o0dStuakp6RFNxaTRxTThHd2ZxbGdwamxnOERVRitzaGVMeDhoTCt4OVhGem92VHhhZnJteQpKUlJBVlFUa2hCN2VzS0txUkY4Qk1qZE9kWVp4SkV2OWp4YTBCd1hjanByUERsajVUVjZrM3dKcWJxNFV0bkVFClZiakVRS3FGVmtmWTRGdUo1TlNQSHBHRWl4OTRQR1FHUnNpV2tHWDB2eDV1ZEhKMFNsWE02cXBNTG55MThGaFcKYndLTlgzdXJjM21JbW4vajN6Y0o1eDFkK0ZsWEFYczFOQlNlVFFJREFRQUJBb0lCQVFESk9UOFBaWGJBaG9obgpBL0FlaW1TMFAwOFMwbWJzRDZWcm9HQkVhanhQNHEyRmVzd0Q3UFFac1R0NCtrbWNUbGZ1aUxtUXFONTBBY1NMCndESEliRFJJYkVuTjdyRUNHS0FqNWpmd0VndFFkV1ZLS3BPUThKYVlyL2E0NjZCdGp5dUxvNFB5R0M4Tlk2bW0KSk0zcUJFSFNsa3ZUNyt1QWhCV1N5ZTdnVTdKZlJQb0NlRlJwYU1NQzNBZDBEYUl0L1BkdDlDZGROd2o1Nis5agpnbC8vYmxObkJJbWp2QTcva2g5Z0w2OVNZVnJRb0c5dm0vVWdGYmRJd2QrdzJoaGhweDZrdUhqUkoyMXhJVi95ClloOWs0UWhQcjd6SWtoUTh5bjExWmh5WmtNQzhYQU15N05LQ21BRklQTko4and2Z0JrdW5QRWsyYVlCZURVYXEKYTMwVndsSWhBb0dCQU9ubThEVzVEUk9jZlNqNFE4enN2Z212aEdNMHp6RjV6bUErNEUrdEViZjR0NnNEVWpTcwpBRG8yRWFpSlp6NzV2THNEN1VaSEt6RkVWL3dudVQ3U2lOQ2JySmFmeDhUcDJVZ2lqVGtXOGdFaEFXUkVKRG41CkZTMzc1UktGZEVjcG1WSFdnc3V6NHovMEwzQkd4bXlZV1F4eDVwRDJOTDQ5WnBUSUhBSG0vWEVUQW9HQkFPSTYKOFkwOFRtTTJiblhiTC9NZ2dZTUpscU95djI3dWVWWXo5b2YzRllGQU1JZTdlYlNncmxTQ093c29EWlltZWdCTQpPcm93UjNBQW5vUDRmakdOYklQak5ZYml2MXFMT2R0bnZQeFlvdEV6K1phVUJTbjlWL2dVRVZGbGdyS3hnVEtyCnNxaS9RTXl5SnBsQlRVa1V1cVlSRHV2NlRaM09XS2lEVW9YVGR2OGZBb0dCQUliYnlmK1BsRVNNWTNWdHZ0bTIKWGRPRHlSYlI2ZXdpeUtTaFcvOVVUL1Q4aUJrbnJ3d0RaNVlvZW9Icnh3VitSQnlucFBSeU1Dc1Z0bzBCOGtLUQpiS1dxUEJZVVJiLzQvSGdrdzd2NHlNdHgxaldUUERmWXJ5ZDJKcHRKS3NPazdtdEsvTnFwK3dweXBhOWNmeWM1CnA0NFBWZHFhdWNvOTZKazd6em9oamxyVkFvR0FmalFEckphSDVERHBUallJZWNrWWR0RlNoOStmaTNMZG5Zay8KYm5vWU5SSnFBRTVGaHM1Y2NpaDBaN1RnWDNMM2ZGTUtML1BlNWt4eUlZenVXUlpjQXZjdFZTSUpQYW1OalNoQgo5VVE5RUJlK2xKSGVqNTRWQlArczZZdUhiY2c0R3R4TnZuVnk0TDVCYWgxVDBBRVFYclFGYnY4amJYVS9ZRUppCk51WFE3R0VDZ1lBMFVOdnVaeFZTRG44ZkJ4QVJjWDN1YjVhb2s1b3dkTEwzU09DUE1wTnJtT0JRajhpSkdUKzUKbnY3ZkgxVFdWaDl5VWRSd2hkODFzNUgvUE8zL215TG1ncTBUY1B2ZXd0RUV3WSsrK1Fwc1lad0hURFhneGJidworK2xtSmFsaTRmem1kLzcySnFvY0dBQlloWkZ0MGpiY1ExUUVjcVVZY0QzODArY05WWlBPK3c9PQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo="
---
# Source: neuron/templates/svc-headless.yaml
apiVersion: v1
kind: Service
metadata:
  name: neuron-headless
  namespace: default
  labels:
    helm.sh/chart: neuron-0.1.0
    app.kubernetes.io/name: neuron
    app.kubernetes.io/instance: neuron
    app.kubernetes.io/version: "2.0.1"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  sessionAffinity: None
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - name: web
      port: 7000
      protocol: TCP
      targetPort: web
    - name: api
      port: 7001
      protocol: TCP
      targetPort: api
  selector:
    app.kubernetes.io/name: neuron
    app.kubernetes.io/instance: neuron
---
# Source: neuron/templates/svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: neuron
  namespace: default
  labels:
    helm.sh/chart: neuron-0.1.0
    app.kubernetes.io/name: neuron
    app.kubernetes.io/instance: neuron
    app.kubernetes.io/version: "2.0.1"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
  - name: web
    port:  7000
    protocol: TCP
    targetPort:  web
    nodePort: null
  - name: api
    port: 7001
    protocol: TCP
    targetPort: api
    nodePort: null
  selector:
    app.kubernetes.io/name: neuron
    app.kubernetes.io/instance: neuron
---
# Source: neuron/templates/statefulset.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: neuron
  namespace: default
  labels:
    helm.sh/chart: neuron-0.1.0
    app.kubernetes.io/name: neuron
    app.kubernetes.io/instance: neuron
    app.kubernetes.io/version: "2.0.1"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  serviceName: neuron-headless
  volumeClaimTemplates:
    - metadata:
        name: neuron-persistence
        namespace: default
        labels:
          app.kubernetes.io/name: neuron
          app.kubernetes.io/instance: neuron
          app.kubernetes.io/managed-by: Helm
      spec:
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: "20Mi"
  selector:
    matchLabels:
      app.kubernetes.io/name: neuron
      app.kubernetes.io/instance: neuron
  template:
    metadata:
      labels:
        app.kubernetes.io/name: neuron
        app.kubernetes.io/instance: neuron
    spec:
      volumes:
        - name: certs
          secret:
            secretName: neuron-certs
            items:
              - key: neuron.pem
                path: neuron.pem
              - key: neuron.key
                path: neuron.key
      containers:
        - name: neuron
          image: "emqx/neuron:2.0.1"
          imagePullPolicy: IfNotPresent
          readinessProbe:
            httpGet:
              port: 7000
            initialDelaySeconds: 5
            periodSeconds: 5
          ports:
          - name: web
            containerPort: 7000
          - name: api
            containerPort: 7001
          volumeMounts:
          - name: neuron-persistence
            mountPath: "/opt/neuron/persistence"
          - name: certs
            mountPath: "/opt/neuron/config/neuron.pem"
            subPath: "neuron.pem"
            readOnly: true
          - name: certs
            mountPath: "/opt/neuron/config/neuron.key"
            subPath: "neuron.key"
            readOnly: true
          resources:
            {}

NOTES:
1. Get the application URL by running these commands:
  export POD_NAME=$(kubectl get pods --namespace default -l "app.kubernetes.io/name=neuron,app.kubernetes.io/instance=neuron" -o jsonpath="{.items[0].metadata.name}")
  export CONTAINER_PORT=$(kubectl get pod --namespace default $POD_NAME -o jsonpath="{.spec.containers[0].ports[0].containerPort}")
  echo "Visit http://127.0.0.1:8080 to use your application"
  kubectl --namespace default port-forward $POD_NAME 8080:$CONTAINER_PORT
