apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "neuron.fullname" . }}-cm-log-conf
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "neuron.labels" . | nindent 4 }}
binaryData:
  {{ range $path, $_ := .Files.Glob (printf "conf/zlog.conf")}}
    {{ $name := base $path }}
    {{- printf "%s" $name}}{{ print ": "}}{{ $.Files.Get $path | b64enc }}
  {{ end }}