apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "neuron.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "neuron.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "neuron.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "neuron.selectorLabels" . | nindent 8 }}
    spec:
      volumes:
        - name: neuron-persistence
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ (tpl .Values.persistence.existingClaim $) | default (include "neuron.fullname" .) }}
          {{- else }}
          emptyDir: {}
          {{- end }}
        - name: neuron-tmp
          {{- if .Values.nngFromExistingPVC.enabled }}
          persistentVolumeClaim:
            claimName: {{ printf "%s" (tpl (default "" .Values.nngFromExistingPVC.existingClaim) .) }}
          {{- else }}
          emptyDir: {}
          {{- end }}
        - name: neuron-logs
          {{- if .Values.logsPVC.enabled }}
          persistentVolumeClaim:
            claimName: {{ printf "%s" (tpl (default "" .Values.logsPVC.existingClaim) .) }}
          {{- else }}
          emptyDir: {}
          {{- end }}
        - name: neuron-log-conf
          configMap:
            name: {{ include "neuron.fullname" . }}-cm-log-conf
            items:
            - key: zlog.conf
              path: zlog.conf
        {{- if .Values.tls.enabled }}
        - name: certs
          secret:
            secretName: {{ include "neuron.tlsSecretName" . }}
            items:
              - key: neuron.pem
                path: neuron.pem
              - key: neuron.key
                path: neuron.key
        {{- end}}
      containers:
        - name: neuron
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              port: {{ .Values.service.web | default 7000 }}
            initialDelaySeconds: 5
            periodSeconds: 5
          {{- end }}
          ports:
          - name: web
            containerPort: {{ .Values.service.ports.api.web | default 7000 }}
            {{- if .Values.hostPorts.enabled }}
            hostPort: {{ .Values.hostPorts.web | default 7000 }}
            {{- end}}
          - name: api
            containerPort: {{ .Values.service.ports.api.port | default 7001 }}
            {{- if .Values.hostPorts.enabled }}
            hostPort: {{ .Values.hostPorts.api | default 7001 }}
            {{- end}}
          volumeMounts:
          - name: neuron-persistence
            mountPath: "/opt/neuron/persistence"
          - name: neuron-tmp
            mountPath: "/tmp"
          - name: neuron-logs
            mountPath: "/opt/neuron/logs"
          - name: neuron-log-conf
            mountPath: "/opt/neuron/config/zlog.conf"
            subPath: "zlog.conf"
          {{- if .Values.tls.enabled }}
          - name: certs
            mountPath: "/opt/neuron/config/neuron.pem"
            subPath: "neuron.pem"
            readOnly: true
          - name: certs
            mountPath: "/opt/neuron/config/neuron.key"
            subPath: "neuron.key"
            readOnly: true
          {{- end }}
          resources:
          {{- toYaml .Values.resources | nindent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}


