name: Check helm version

on:
  push:
    paths:
      - deploy/charts/neuron/templates/**
  pull_request:
    paths:
      - deploy/charts/neuron/templates/**

jobs:
  check-helm-version:
    runs-on: ubuntu-latest
    steps:
      - run: minikube start
      - uses: actions/checkout@v2
      - name: Update helm
        run: |
          helm repo add emqx https://repos.emqx.io/charts
          helm repo update
      - name: Check helm version
        run: |
          old=$(helm show chart emqx/neuron |egrep "^version" | sed -r 's|^version:[[:space:]]([0-9]+.[0-9]+.[0-9]+)$|\1|g')
          now=$(egrep "^version" deploy/charts/neuron/Chart.yaml | sed -r 's|^version:[[:space:]]([0-9]+.[0-9]+.[0-9]+)$|\1|g')
          if [ "$old" = "$now" ];then
            echo "Need update version for Chart.yaml"
            exit 1
          fi
