name: Test helm

on:
  push:
    tags:
      - "*"
  pull_request:

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - run: minikube start --kubernetes-version="v1.23.0"
      - uses: actions/checkout@v2
      - name: Deploy neuron by helm
        shell: bash
        run: |
          helm install neuron deploy/charts/neuron\
            --set image.repository="emqx/neuron"\
            --set image.tag="2.2.14"
      - name: Check deployment
        timeout-minutes: 5
        run: |
          set -euo pipefail
          while [ "$(kubectl get pods -o json | jq '.items[0].status.containerStatuses[] | select(.ready==true) | .containerID')" = "" ]; do
            echo "=============================="
            kubectl get pods
            echo "=============================="
            echo "waiting neuron started"
            sleep 10
          done


